- hosts: localhost
  become: true
  tasks:
  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes
  - name: Install zsh
    apt: name=zsh
    tags:
    - zsh
  - name: Change shell
    shell: chsh -s `which zsh`
    tags:
    - zsh
  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    tags:
    - zsh
  - name: install node
    apt:
      name: ['nodejs', 'npm']
    tags:
    - node